### ISSUE TITLE
How to add options for phantom?

### ISSUE THREAD

**Issue by zaaack** [binded/phantom-pool#1]
Looks into the code, it doesn't pass any option to `phantom.create()`, is there any way to add parameters for phantom?

**Comment by olalonde** [comment]
I don't think right now though I'd be happy to merge a pull request

**Comment by zaaack** [comment]
@olalonde OK, the PR is ready.

**Comment by olalonde** [comment]
Thanks, merged https://github.com/blockai/phantom-pool/pull/2
