### ISSUE TITLE
Validate a phantom instance before reusing it

### ISSUE THREAD

**Issue by jondeodat** [binded/phantom-pool#4]
Hi,

I was willing to create a fork in order to add the possibility to validate a resource each time it is borrowed when I saw @mikedaly pull request. So once it is merged, no need for another one. Cool. (Any roadmap regarding this merging ? I would be glad to use it as soon as possible :dancing_men:)

In any case, the reason I want the 'validate' functionality is because I think the pool should check the phantom instance is still functional before giving it.

I saw that by accident. Make the test : 
- launch a very long phantom evaluate script
- kill the phantom process (via the task manager for instance)
- the phantom instance will stay in the pool and be provided again and again although it is not usable anymore (Error reading from stdin…)

Would you know a performant way to check the phantom instance validity ? The only option I see when reading [phantomjs-node](https://github.com/amir20/phantomjs-node) documentation would be by creating a web page via [#createPage](https://github.com/amir20/phantomjs-node#phantomcreatepage) but it seems a bit much.

**Comment by olalonde** [comment]
Hi @jdat82 , I just merged https://github.com/blockai/phantom-pool/pull/3 and published as `phantom-pool@1.2.0`. I am not really sure how to validate the phantom instance validity but the maxUses param should be pretty helpful. I'd be open to your suggestions if you find a way to check validity programmatically.

**Comment by jondeodat** [comment]
Very helpful. Thank you for your reactivity.

Regarding checking the validity. I guess it depends on your definition of "validity" which might be different from one project to another. 

Nonetheless, I presume that being able to create a page via `#createPage` is a good sign of health. Maybe going even further by opening a very light and fast page would be even more compelling. 

So at least:

```js
createPhantomPool({
…
validator:function (instance) {
    return instance.createPage();
},
…
});
```

**Comment by mikedaly** [comment]
This seems a very expensive validation to do on each process request, but I guess it depends on the frequency of requests and how long your actual work is once you get a valid process. I don't know of a better way.

I think that you would want to put a timeout on that request if you went that route, so that if `.createPage` never returns, you have an opportunity to kill it and fail the validation promise.

**Comment by jondeodat** [comment]
@mikedaly: I agree. 

As "validity" has different meaning from one project to another I guess there is no need for this issue anymore. Each one might be willing to pay a different cost for validity. I will close it.
