### ISSUE TITLE
Phantom pool fails to run on Alpine Linux

### ISSUE THREAD

**Issue by freddymercury** [binded/phantom-pool#7]
I am running Phantom-pool in a docker container which is running Alpine Linux.

Here is the error:
`/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory`

The libfontconfig.so lib does not exist for Alpine Linux.

I did digging and found that the phantom-prebuilt v. 2.1.4 does have this problem and could be resolved by updating to 2.1.8 or greater.

https://github.com/amir20/phantomjs-node/issues/514

Can the dependency on prebuilt be updated?  Also, if and when the update happens how can I get the respective npm module updated?

Thanks

**Comment by freddymercury** [comment]
Alpine linux version 3.4 / 3.5

**Comment by freddymercury** [comment]
Also, there is an alternative work around -- I haven't tried it but an update may be best.

https://github.com/Overbryd/docker-phantomjs-alpine/releases/tag/2.11

**Comment by olalonde** [comment]
Hmmm, maybe we should make `phantom` a peer dependency. Would that help?

**Comment by freddymercury** [comment]
Yeah, that may help -- i think.. the result of having be a peer dependency would be that i can I specify my own version of phantom-prebuilt in (myApp)  package.json?

**Comment by mikedaly** [comment]
`peerDependencies` is deprecated in npm3, so I don't think that a good solution.

The phantom-prebuilt dependency is actually in the `phantom` library, not this one. That library has the following in its dependency list: `"phantomjs-prebuilt": "^2.1.4"`

With npm3, I think all you would need to do is add a newer phantomjs-prebuilt version to your application's dependencies, as you suggest. npm3 will find your dependency, and it will satisfy the dependency of the phantom library. (I suppose we could add a dependency to phantom-pool, but I don't think that's the right approach.)
