### ISSUE TITLE
How to cleanup phantom instance before reuse

### ISSUE THREAD

**Issue by aro1976** [binded/phantom-pool#8]
Hi,

In the readme you say it is important to cleanup phantom instances:
> When using phantom-pool, you should be aware that the phantom instance you are getting might not be in a completely clean state. It could have browser history, cookies or other persistent data from a previous use.

I checked examples in this repository and [phantomjs-node](https://github.com/amir20/phantomjs-node) and I didn't find any documentation or example about how to cleanup a phantom instance before returning to pool.

The excerpt below from [phantoms-node](https://github.com/amir20/phantomjs-node/blob/master/src/phantom.js) says **exit** and **kill** kills the phantom process in order to cleanup.

```
    /**
     * Cleans up and end the phantom process
     */
    exit(): Promise<Response> {
        clearInterval(this.heartBeatId);
        if (this.commands.size > 0) {
            this.logger.warn('exit() was called before waiting for commands to finish. ' +
                'Make sure you are not calling exit() too soon.');
        }
        return this.execute('phantom', 'invokeMethod', ['exit']);
    }

    /**
     * Clean up and force kill this process
     */
    kill(errmsg: string = 'Phantom process was killed'): void {
        this._rejectAllCommands(errmsg);
        this.process.kill('SIGKILL');
    }
```

 I think this is not what you meant. How do I suppose to clean it up?

**Comment by olalonde** [comment]
If you really need a clean instance, killing the phantom process should work.

**Comment by mikedaly** [comment]
...although if you just kill the phantom process after each use, you aren't getting any benefit from the pool.

I think the "cleaning" that the README refers to is other browser artifacts, such as cookies and local storage. Since the same browser instance can be reused, those can "leak" across one use to another. You can manually clear your cookies before releasing the phantom instance using `phantom.clearCookies()`, and I'm sure there must be something similar for local storage.

**Comment by olalonde** [comment]
Indeed... I'm not sure what else. Feel free to send a PR if you find out.

**Comment by aro1976** [comment]
I think the behavior expected should be similar to an anonymous browsing session, it should hold cookie values and local storage between in a given page flow, but when after closing a page it should clean all information.
