### ISSUE TITLE
Example are all broken with node 8.1.1

### ISSUE THREAD

**Issue by George3d6** [binded/phantom-pool#9]
Trying to run the examples with node v8.1.1 results in an error:

```
import phantom from 'phantom'
^^^^^^
SyntaxError: Unexpected token import

```
Also, the front page example is wrong (missing and miss placed comas that make the object structure wrong)... and using:

`const phantom_pool = require('phantom-pool');`

instead of import resulting in an error when trying to create the pool:

`const pool = phantom_pool();`

**Comment by olalonde** [comment]
Oops yeah, please send a PR

**Comment by George3d6** [comment]
Will do one to fix the readme and to add the documentation about how to run this, since as far as I see this only works if you run with:

node --harmony ... which is not specified.

Would you also like me to do a pool request that adds a plain node compatible version (no spread op and no import export) ?

**Comment by George3d6** [comment]
Ups, my bad, --harmony apparently doesn't enable import/export. So you'd either need a 'compiled' version for this or some flag that enables them to run (but I can't find any options to do so atm :/)

**Comment by olalonde** [comment]
Sure, it's possible my babelrc doesn't support older node versions. Feel free to adjust it as well.

**Comment by George3d6** [comment]
Ok... dug into it a bit, decided to remove all the dependencies except phanomt and generic pool. The package was way too heavy for what it did... I striped it to a version that's compatible with node6 + with no linting (as long as harmony is used for the spread) and should work 100% in whatever configuration you guys used before with bable.

Considering there is deprecation inside the package.json, the npm dwonloaded package wasn't working and the readme example was broken I'd say it benefits everyone to bring this to a smaller state where it can be maintained if the need arises without code arechology skills.
